version: "2"
services:
  app:
    container_name: api
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - mydata:/data/db
    ports:
      - "27017:27017"
volumes:
  mydata: